name: 'Hello World'
description: 'Greet someone'
inputs:
  who-to-greet:  # id of input
    description: 'Who to greet'
    required: true
    default: 'World'
outputs: #⬅️ Output declaration for ACTION
  random-number:
    description: "Random number"
    value: ${{ steps.random-number-generator.outputs.random-number }} #⬅️ As you can see, it's not much different from reference in workflow
runs:
  using: "composite" #⬅️ Here we specify what this is.
  steps: #⬅️ Steps like in workflow. We don't have jobs here (which is obvious, because we're writing an action) 
    - name: Set Greeting
      run: echo "Hello $INPUT_WHO_TO_GREET."
      shell: bash
      env:
        INPUT_WHO_TO_GREET: ${{ inputs.who-to-greet }}  #⬅️ Getting input from action

    - name: Random Number Generator
      id: random-number-generator
      run: echo "random-number=$(echo $RANDOM)" >> $GITHUB_OUTPUT
      shell: bash